--- #YAML:1.0
name:               WebService-Google-Closure
version:            0.10
abstract:           Perl interface to the Google Closure Javascript compiler service
author:
    - Magnus Erixzon <magnus@erixzon.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::MOP:           1.09
    File::Slurp:          0
    JSON:                 0
    LWP::UserAgent::Mockable:  0
    Moose:                0
    MooseX::Types:        0
    Perl6::Junction:      0
    Test::Class:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
